//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMeServices.Models.Resources.ApiUrls", typeof(ApiUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/.
        /// </summary>
        public static string PaymentAPIDhofar {
            get {
                return ResourceManager.GetString("PaymentAPIDhofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/Paymentrequest/GetRequestStatus?Token=.
        /// </summary>
        public static string PaymentAPIGetRequestStatusDhofar {
            get {
                return ResourceManager.GetString("PaymentAPIGetRequestStatusDhofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/Paymentrequest/GetRequestStatus?Token=.
        /// </summary>
        public static string PaymentAPIGetRequestStatusODP {
            get {
                return ResourceManager.GetString("PaymentAPIGetRequestStatusODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/.
        /// </summary>
        public static string PaymentAPIODP {
            get {
                return ResourceManager.GetString("PaymentAPIODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/Paymentrequest/OpenPaymentRequest.
        /// </summary>
        public static string PaymentAPIOpenRequestDhofar {
            get {
                return ResourceManager.GetString("PaymentAPIOpenRequestDhofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/ePaymentAPI/API/Paymentrequest/OpenPaymentRequest.
        /// </summary>
        public static string PaymentAPIOpenRequestODP {
            get {
                return ResourceManager.GetString("PaymentAPIOpenRequestODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/sso/default.aspx?noguid=1&amp;returnUrl=.
        /// </summary>
        public static string SSODhofar {
            get {
                return ResourceManager.GetString("SSODhofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dhofar.gov.om/sso/default.aspx?noguid=1&amp;returnUrl=.
        /// </summary>
        public static string SSOODP {
            get {
                return ResourceManager.GetString("SSOODP", resourceCulture);
            }
        }
    }
}
