//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayName_Ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayName_Ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMeServices.Models.Resources.DisplayName_Ar", typeof(DisplayName_Ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجمع السكني.
        /// </summary>
        public static string BuildingComplex {
            get {
                return ResourceManager.GetString("BuildingComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المبنى.
        /// </summary>
        public static string BuildingTypeID {
            get {
                return ResourceManager.GetString("BuildingTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة التنفيذ.
        /// </summary>
        public static string ConstructedArea {
            get {
                return ResourceManager.GetString("ConstructedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالك المكتب الهندسي.
        /// </summary>
        public static string CosultantOwner {
            get {
                return ResourceManager.GetString("CosultantOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CS_NO {
            get {
                return ResourceManager.GetString("CS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القطعة.
        /// </summary>
        public static string DistrictNo {
            get {
                return ResourceManager.GetString("DistrictNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات قسم تراخيص للاستشاري.
        /// </summary>
        public static string DmEngineerComments {
            get {
                return ResourceManager.GetString("DmEngineerComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات للإدارة.
        /// </summary>
        public static string DMEngineerNotes {
            get {
                return ResourceManager.GetString("DMEngineerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف.
        /// </summary>
        public static string DmFileNumber {
            get {
                return ResourceManager.GetString("DmFileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات المفتش.
        /// </summary>
        public static string DmInspectorComments {
            get {
                return ResourceManager.GetString("DmInspectorComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الترخيص.
        /// </summary>
        public static string DMLicenseComments {
            get {
                return ResourceManager.GetString("DMLicenseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات مدير الدائرة.
        /// </summary>
        public static string DMManagerNotes {
            get {
                return ResourceManager.GetString("DMManagerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات قسم رقابة البناء.
        /// </summary>
        public static string DmSupervisionComments {
            get {
                return ResourceManager.GetString("DmSupervisionComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموظف.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف.
        /// </summary>
        public static string FileNo {
            get {
                return ResourceManager.GetString("FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعيين.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الوظيفة.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكروكي.
        /// </summary>
        public static string KrokiNO {
            get {
                return ResourceManager.GetString("KrokiNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساحة الكلية لقطعة الأرض.
        /// </summary>
        public static string LandArea {
            get {
                return ResourceManager.GetString("LandArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عقد بيع رقم.
        /// </summary>
        public static string LandDeedNo {
            get {
                return ResourceManager.GetString("LandDeedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ايصال سند الملكية.
        /// </summary>
        public static string LandDeedReceiptDate {
            get {
                return ResourceManager.GetString("LandDeedReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم ايصال سند الملكية.
        /// </summary>
        public static string LandDeedReceiptNo {
            get {
                return ResourceManager.GetString("LandDeedReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم القبيلة.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الترخيص.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الطوابق المراد تنفيذها.
        /// </summary>
        public static string NumberOfFloors {
            get {
                return ResourceManager.GetString("NumberOfFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم المدني للمالك.
        /// </summary>
        public static string OwnerCivilId {
            get {
                return ResourceManager.GetString("OwnerCivilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المالك.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة / القرية.
        /// </summary>
        public static string RegionID {
            get {
                return ResourceManager.GetString("RegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخدمة المطلوبة.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المربع.
        /// </summary>
        public static string SquareLetterID {
            get {
                return ResourceManager.GetString("SquareLetterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رأي المفتش.
        /// </summary>
        public static string SupervisionStatus {
            get {
                return ResourceManager.GetString("SupervisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث.
        /// </summary>
        public static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع استعمال قطع الأرض.
        /// </summary>
        public static string UseTypeID {
            get {
                return ResourceManager.GetString("UseTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الولاية.
        /// </summary>
        public static string WelayahID {
            get {
                return ResourceManager.GetString("WelayahID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رأي المهندس.
        /// </summary>
        public static string WorkflowStatus {
            get {
                return ResourceManager.GetString("WorkflowStatus", resourceCulture);
            }
        }
    }
}
