//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayName_Ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayName_Ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMeServices.Models.Resources.DisplayName_Ar", typeof(DisplayName_Ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة قطعة الأرض.
        /// </summary>
        public static string ConstructedArea {
            get {
                return ResourceManager.GetString("ConstructedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعمال قطعة الأرض.
        /// </summary>
        public static string ConstructionType {
            get {
                return ResourceManager.GetString("ConstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CS_NO {
            get {
                return ResourceManager.GetString("CS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القطعة.
        /// </summary>
        public static string DistrictNo {
            get {
                return ResourceManager.GetString("DistrictNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموظف.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف.
        /// </summary>
        public static string FileNo {
            get {
                return ResourceManager.GetString("FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعيين.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الوظيفة.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكروكي.
        /// </summary>
        public static string KrokiNO {
            get {
                return ResourceManager.GetString("KrokiNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم القبيلة.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الترخيص.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الطوابق المراد بنائها.
        /// </summary>
        public static string NumberOfFloors {
            get {
                return ResourceManager.GetString("NumberOfFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم المدني للمالك.
        /// </summary>
        public static string OwnerCivilId {
            get {
                return ResourceManager.GetString("OwnerCivilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المالك.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل العلمي.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المربع.
        /// </summary>
        public static string SquareArea {
            get {
                return ResourceManager.GetString("SquareArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث.
        /// </summary>
        public static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
