//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldControlServices
    {
        public int ID { get; set; }
        public long BldPermitID { get; set; }
        public int ServiceTypeID { get; set; }
        public int Status { get; set; }
    
        public virtual BldControlServicesTypes BldControlServicesTypes { get; set; }
        public virtual BldPermits BldPermits { get; set; }
    }
}
