//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldIndustrialAreasSurvey
    {
        public int IndustrialSurveyID { get; set; }
        public int WelayahID { get; set; }
        public int RegionID { get; set; }
        public int SquareLetterID { get; set; }
        public string RegionArName { get; set; }
        public string RegionEnName { get; set; }
        public Nullable<int> UseTypeID { get; set; }
        public string LocationCoordinates { get; set; }
        public int BuildingsCount { get; set; }
        public int FlatsCount { get; set; }
        public int IndustrialShopsCount { get; set; }
        public int CommercialShopsCount { get; set; }
        public string TransactNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public Nullable<int> BuildingsTypeID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedON { get; set; }
    
        public virtual BldBuildingTypes BldBuildingTypes { get; set; }
        public virtual BldLandUseTypes BldLandUseTypes { get; set; }
        public virtual BldRegions BldRegions { get; set; }
        public virtual BldSquareLetters BldSquareLetters { get; set; }
        public virtual BldWelyat BldWelyat { get; set; }
    }
}
