//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldLandSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BldLandSurvey()
        {
            this.BldWorkersHousingDetails = new HashSet<BldWorkersHousingDetails>();
        }
    
        public int SurveyID { get; set; }
        public int WelyahID { get; set; }
        public int RegionID { get; set; }
        public int SquareLetterID { get; set; }
        public string LandNo { get; set; }
        public Nullable<int> LandUseTypeID { get; set; }
        public Nullable<int> BuildingTypeID { get; set; }
        public Nullable<int> BuildingsCount { get; set; }
        public Nullable<int> FlatsCount { get; set; }
        public Nullable<int> ShopsCount { get; set; }
        public Nullable<int> RoomsCount { get; set; }
        public string Notes { get; set; }
        public string TransactNo { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public Nullable<int> IndustrialSurveyID { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public string ElectricityAccountNo { get; set; }
        public string LandCoordinates { get; set; }
        public Nullable<int> CollectiveResidenceType { get; set; }
        public Nullable<long> ConsultantCivilId { get; set; }
        public Nullable<long> OwnerCivilId { get; set; }
    
        public virtual BldRegions BldRegions { get; set; }
        public virtual BldWelyat BldWelyat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BldWorkersHousingDetails> BldWorkersHousingDetails { get; set; }
    }
}
