//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldOwners
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CivilID { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> BldPermitId { get; set; }
    
        public virtual BldPermits BldPermits { get; set; }
    }
}
