//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldPermitsAttachmentDetails
    {
        public int Id { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentContentType { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string AttachmentPath { get; set; }
        public string Description { get; set; }
        public int BldPermitAttId { get; set; }
        public byte[] AttachmentStream { get; set; }
        public Nullable<int> DmEngineerNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> AttachmentTypeId { get; set; }
        public Nullable<int> ConsultantCivilId { get; set; }
    
        public virtual BldPermitsAttachments BldPermitsAttachments { get; set; }
    }
}
