//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldPermitsAttachments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BldPermitsAttachments()
        {
            this.BldPermitsAttachmentDetails = new HashSet<BldPermitsAttachmentDetails>();
        }
    
        public long Id { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentContentType { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string AttachmentPath { get; set; }
        public string Description { get; set; }
        public long BldPermitId { get; set; }
        public byte[] AttachmentStream { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> AttachmentTypeId { get; set; }
    
        public virtual BldAttachmentTypes BldAttachmentTypes { get; set; }
        public virtual BldPermits BldPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BldPermitsAttachmentDetails> BldPermitsAttachmentDetails { get; set; }
    }
}
