//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BldPayment()
        {
            this.BldPaymentDetails = new HashSet<BldPaymentDetails>();
        }
    
        public int PaymentID { get; set; }
        public Nullable<int> BldPermitId { get; set; }
        public Nullable<decimal> PaymentTotalAmount { get; set; }
        public string TokenID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> FeesDate { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string Transactionid { get; set; }
        public Nullable<int> Paymentrequestid { get; set; }
        public string Referenceid { get; set; }
        public string Bankpaymentid { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> BankResponseID { get; set; }
    
        public virtual BldPermits BldPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BldPaymentDetails> BldPaymentDetails { get; set; }
    }
}
