//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldServiceFees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BldServiceFees()
        {
            this.BldPaymentDetails = new HashSet<BldPaymentDetails>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<decimal> ServiceFees { get; set; }
        public string ServiceUnit { get; set; }
        public Nullable<int> SeviceFinancialItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BldPaymentDetails> BldPaymentDetails { get; set; }
    }
}
