//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldSupervisionServicesTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BldSupervisionServicesTypes()
        {
            this.BldSupervisionServices = new HashSet<BldSupervisionServices>();
        }
    
        public int ID { get; set; }
        public string ServiceNameAR { get; set; }
        public string ServiceNameEn { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public string CssClassName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BldSupervisionServices> BldSupervisionServices { get; set; }
    }
}
