//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldTransactions
    {
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> BldPermitId { get; set; }
        public Nullable<int> BldSupervisionId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual BldPermits BldPermits { get; set; }
        public virtual BldTransactionTypes BldTransactionTypes { get; set; }
        public virtual BldSupervisionServices BldSupervisionServices { get; set; }
    }
}
