//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BldWorkersHousingDetails
    {
        public int Id { get; set; }
        public int SurveyID { get; set; }
        public string WorkerName { get; set; }
        public int WorkerID { get; set; }
        public Nullable<int> WorkerPhone { get; set; }
    
        public virtual BldLandSurvey BldLandSurvey { get; set; }
    }
}
