//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultantOccupations
    {
        public int OccupationID { get; set; }
        public string OccupationDescArabic { get; set; }
        public string OccupationDescEnglish { get; set; }
    }
}
