//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class docs
    {
        public int docID { get; set; }
        public int pdfID { get; set; }
        public System.DateTime docDate { get; set; }
        public Nullable<System.DateTime> docDateModified { get; set; }
        public int docStatus { get; set; }
        public int docSettings { get; set; }
        public string docFileName { get; set; }
        public string docXml { get; set; }
        public byte[] docOutputData { get; set; }
    }
}
