//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.EmployeeGroups = new HashSet<EmployeeGroups>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string GRADE { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public int EMP_NO { get; set; }
        public string QUALIFICATION { get; set; }
        public Nullable<int> FILE_NO { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> MOBILE_NO { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<int> JobId { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public Nullable<int> SiteCd { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGroups> EmployeeGroups { get; set; }
    }
}
