//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGroups
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
