//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HsPermitsInspection
    {
        public Nullable<int> InspectorNo { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string InpectionNote { get; set; }
        public Nullable<long> HsPermitId { get; set; }
        public long Id { get; set; }
        public Nullable<long> PermitDurationId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual HsPermitDuration HsPermitDuration { get; set; }
    }
}
