//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HsPermitSubActivity
    {
        public Nullable<int> ActivityCode { get; set; }
        public Nullable<int> SubCode { get; set; }
        public string SubName { get; set; }
        public Nullable<int> Price { get; set; }
        public int Id { get; set; }
        public Nullable<int> PermitTypeId { get; set; }
    
        public virtual HsPermitType HsPermitType { get; set; }
    }
}
