//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HsPermitAdvertisement
    {
        public Nullable<int> AdvPermitTypeId { get; set; }
        public Nullable<int> AdvActivityTypeId { get; set; }
        public string AdvLocation { get; set; }
        public string AdvStreet { get; set; }
        public Nullable<int> AdvTotalBoards { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> RevenueReceiptDate { get; set; }
        public Nullable<int> RevenueReceiptNo { get; set; }
        public Nullable<long> HsPermitId { get; set; }
        public long Id { get; set; }
    
        public virtual HsPermits HsPermits { get; set; }
    }
}
