//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HsPermitDuration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HsPermitDuration()
        {
            this.HsContractAttachments = new HashSet<HsContractAttachments>();
            this.HsPermitsInspection = new HashSet<HsPermitsInspection>();
        }
    
        public Nullable<System.DateTime> PermitStartDate { get; set; }
        public Nullable<System.DateTime> PermitEndDate { get; set; }
        public Nullable<long> RevenueReceiptNo { get; set; }
        public Nullable<System.DateTime> RevenueReceiptDate { get; set; }
        public Nullable<decimal> RevenuePermitFees { get; set; }
        public Nullable<long> HsPermitId { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string ContractNo { get; set; }
        public Nullable<decimal> ContractMonthlyFees { get; set; }
        public Nullable<int> WorkflowStatus { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentContentType { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string AttachmentPath { get; set; }
        public byte[] AttachmentStream { get; set; }
        public string Description { get; set; }
        public Nullable<int> InspectorNo { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string HeadSectionNotes { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> CivilId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HsContractAttachments> HsContractAttachments { get; set; }
        public virtual HsPermits HsPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HsPermitsInspection> HsPermitsInspection { get; set; }
    }
}
