//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class keys
    {
        public int keyID { get; set; }
        public int docID { get; set; }
        public string keyData { get; set; }
        public System.DateTime keyExpires { get; set; }
        public int keySettings { get; set; }
    }
}
