//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupTypes
    {
        public int LookupId { get; set; }
        public string LookupNameAr { get; set; }
        public string LookupNameEn { get; set; }
        public string LookupParentDesc { get; set; }
        public int LookupParentId { get; set; }
    }
}
