//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MociData
    {
        public long COMMERCIAL_NO { get; set; }
        public string COMMERCIAL_NAME { get; set; }
        public string COMMERCIAL_DATE { get; set; }
        public string LEGAL_FORM { get; set; }
        public Nullable<int> PHONE_NO { get; set; }
        public string EMAIL { get; set; }
        public string GOVERNORATE { get; set; }
        public string STATE { get; set; }
        public string FULL_NAME { get; set; }
        public string CIVIL_ID { get; set; }
        public long ID { get; set; }
    }
}
