//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class objs
    {
        public int objID { get; set; }
        public int docID { get; set; }
        public int objType { get; set; }
        public int objSettings { get; set; }
        public byte[] objData { get; set; }
        public int objDataLength { get; set; }
    }
}
