//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdfs
    {
        public int pdfID { get; set; }
        public System.DateTime pdfDate { get; set; }
        public int pdfStatus { get; set; }
        public int pdfVersion { get; set; }
        public int pdfPageLoaded { get; set; }
        public int pdfPageCount { get; set; }
        public int pdfUserRights { get; set; }
        public int pdfDpi { get; set; }
        public int pdfDpiHigh { get; set; }
        public byte[] pdfData { get; set; }
        public int pdfDataLength { get; set; }
        public byte[] pdfDataHash { get; set; }
        public byte[] pdfPassHash { get; set; }
        public string pdfXml { get; set; }
        public string pdfText { get; set; }
    }
}
