//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pges
    {
        public int pdfID { get; set; }
        public int docID { get; set; }
        public int keyID { get; set; }
        public System.DateTime pgeDate { get; set; }
        public int pgeStatus { get; set; }
        public int pgeNumber { get; set; }
        public int pgeImageType { get; set; }
        public byte[] pgeImageData { get; set; }
    }
}
