//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMeServices.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevFinancialSubItems
    {
        public int Id { get; set; }
        public Nullable<long> Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> FinancialItemId { get; set; }
        public string ChargeType { get; set; }
        public Nullable<long> ChargeAmount { get; set; }
        public Nullable<long> SiteCd { get; set; }
    }
}
